# -*- coding: utf-8 -*-
"""MRI_4_fairness_audit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDa9dInkpw2ujA_q4yAGXYzbnhBjm0Xv
"""

#  Session Reload

from google.colab import drive
drive.mount('/content/drive')

import os, gc, warnings
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
import numpy as np
import tensorflow as tf
warnings.filterwarnings('ignore')

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

PROJECT_ROOT  = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
CLASS_NAMES   = ['glioma', 'meningioma', 'notumor', 'pituitary']
PRED_DIR      = f'{PROJECT_ROOT}/results/predictions'
METRICS_DIR   = f'{PROJECT_ROOT}/results/metrics'
FIGURES_DIR   = f'{PROJECT_ROOT}/results/figures'

# Load saved arrays
y_true        = np.load(f'{PRED_DIR}/y_true.npy')
y_pred_effnet = np.load(f'{PRED_DIR}/y_pred_effnet_final.npy')
uncertainty   = np.load(f'{PRED_DIR}/uncertainty.npy')
mc_pred_class = np.load(f'{PRED_DIR}/mc_pred_class.npy')

print(f"y_true:       {y_true.shape}")
print(f"y_pred:       {y_pred_effnet.shape}")
print(f"uncertainty:  {uncertainty.shape}")
print(f"Overall acc:  {np.mean(y_pred_effnet == y_true):.4f}")
print(f"\nPer-class accuracy:")
for i, cls in enumerate(CLASS_NAMES):
    mask = y_true == i
    acc  = np.mean(y_pred_effnet[mask] == y_true[mask])
    unc  = uncertainty[mask].mean()
    print(f"  {cls:>12}: acc={acc:.4f}  mean_unc={unc:.4f}")

print("\nPhase 4 ready — Fairness Audit")

import numpy as np
import tensorflow as tf
import cv2
import os
import warnings
warnings.filterwarnings('ignore')

os.environ['CUDA_VISIBLE_DEVICES'] = '-1' # CPU-only, inference is cheap

# Define paths and parameters (from cell 6bG2RW34ielM or ZgCqPOU52KsO)
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
CLAHE_DIR    = f'{PROJECT_ROOT}/data/clahe_processed'
PRED_DIR     = f'{PROJECT_ROOT}/results/predictions'
METRICS_DIR  = f'{PROJECT_ROOT}/results/metrics'
FIGURES_DIR  = f'{PROJECT_ROOT}/results/figures'
CLASS_NAMES  = ['glioma', 'meningioma', 'notumor', 'pituitary']
IMG_SIZE     = (224, 224)
BATCH_SIZE   = 32

# Load y_true and y_pred_effnet (from cell 6bG2RW34ielM or iq9B0alFWXGT)
y_true        = np.load(f'{PRED_DIR}/y_true.npy')
y_pred_effnet = np.load(f'{PRED_DIR}/y_pred_effnet_final.npy')

# Load the model (from cell 6bG2RW34ielM or ZgCqPOU52KsO)
effnet_model = tf.keras.models.load_model(
    f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2b.keras'
)

# Load X_test (from cell 6bG2RW34ielM or ZgCqPOU52KsO)
print("Loading test images for robustness testing...")
test_ds = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Testing',
    seed=42, image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=False
)
X_list, y_list = [], []
for x_batch, y_batch in test_ds:
    X_list.append(x_batch.numpy())
    y_list.append(y_batch.numpy())
X_test = np.concatenate(X_list, axis=0).astype(np.uint8)
y_check = np.concatenate(y_list, axis=0)
del X_list, y_list
print(f"Loaded: {X_test.shape}, labels match: {np.array_equal(y_check, y_true)}")

# Define apply_gaussian_noise function (from cell 6bG2RW34ielM)
def apply_gaussian_noise(images, sigma):
    noisy = images.astype(np.float32) + np.random.normal(0, sigma, images.shape)
    return np.clip(noisy, 0, 255).astype(np.uint8)

# Define predict_accuracy function (from cell 6bG2RW34ielM)
def predict_accuracy(images):
    preprocessed = tf.keras.applications.efficientnet.preprocess_input(
        images.astype(np.float32)
    )
    preds = []
    for i in range(0, len(preprocessed), BATCH_SIZE):
        batch = tf.constant(preprocessed[i:i+BATCH_SIZE])
        pred  = effnet_model(batch, training=False).numpy()
        preds.append(np.argmax(pred, axis=1))
    preds = np.concatenate(preds)
    return float(np.mean(preds == y_true))

# Initialize baseline_acc and results dictionary (from cell 6bG2RW34ielM or ZgCqPOU52KsO)
baseline_acc = float(np.mean(y_pred_effnet == y_true))
results = {'baseline': baseline_acc}

# Original code from the selected cell
print("\nRunning Gaussian noise sweep...")
for sigma in [15, 25]:
    noisy = apply_gaussian_noise(X_test, sigma)
    acc = predict_accuracy(noisy)
    results[f'gaussian_noise_sigma{sigma}'] = acc
    print(f"  sigma={sigma}: {acc:.4f}")

#Simulate demographics + Fairlearn audit

!pip install -q fairlearn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
from fairlearn.metrics import MetricFrame, demographic_parity_difference, equalized_odds_difference
from sklearn.metrics import accuracy_score, recall_score, precision_score
warnings.filterwarnings('ignore')

#  Simulate demographic metadata
# Dataset has no real demographics — standard practice is to
# simulate and disclose. We assign age/gender based on known
# epidemiological patterns in brain tumor literature:
# Glioma: slight male predominance, wider age range
# Meningioma: female predominance, older age
# Pituitary: younger patients, balanced gender
# Notumor: balanced

np.random.seed(SEED)
n = len(y_true)

# Gender simulation (0=Male, 1=Female)
gender = np.zeros(n, dtype=int)
for i in range(n):
    cls = y_true[i]
    if cls == 0:    # glioma — 60% male
        gender[i] = np.random.choice([0,1], p=[0.60, 0.40])
    elif cls == 1:  # meningioma — 65% female
        gender[i] = np.random.choice([0,1], p=[0.35, 0.65])
    elif cls == 2:  # notumor — 50/50
        gender[i] = np.random.choice([0,1], p=[0.50, 0.50])
    else:           # pituitary — 55% female
        gender[i] = np.random.choice([0,1], p=[0.45, 0.55])

# Age group simulation (0=18-40, 1=41-60, 2=61+)
age_group = np.zeros(n, dtype=int)
for i in range(n):
    cls = y_true[i]
    if cls == 0:    # glioma — peaks 41-60
        age_group[i] = np.random.choice([0,1,2], p=[0.25, 0.50, 0.25])
    elif cls == 1:  # meningioma — peaks 61+
        age_group[i] = np.random.choice([0,1,2], p=[0.15, 0.40, 0.45])
    elif cls == 2:  # notumor — younger
        age_group[i] = np.random.choice([0,1,2], p=[0.45, 0.35, 0.20])
    else:           # pituitary — younger
        age_group[i] = np.random.choice([0,1,2], p=[0.50, 0.35, 0.15])

gender_labels   = np.array(['Male','Female'])[gender]
age_labels      = np.array(['18-40','41-60','61+'])[age_group]

print("Simulated demographics:")
print(f"  Male: {(gender==0).sum()}  Female: {(gender==1).sum()}")
print(f"  18-40: {(age_group==0).sum()}  41-60: {(age_group==1).sum()}  61+: {(age_group==2).sum()}")

# Binary correct/incorrect for MetricFrame
y_correct = (y_pred_effnet == y_true).astype(int)

# Fairlearn MetricFrame — Gender

print("FAIRLEARN — Gender Analysis")


mf_gender = MetricFrame(
    metrics={
        'accuracy':  accuracy_score,
        'precision': lambda y, yp: precision_score(y, yp, zero_division=0),
        'recall':    lambda y, yp: recall_score(y, yp, zero_division=0),
    },
    y_true=y_correct,
    y_pred=y_correct,  # We audit correctness as binary outcome
    sensitive_features=gender_labels
)

# Per-group accuracy
for grp in ['Male','Female']:
    mask = gender_labels == grp
    acc  = np.mean(y_pred_effnet[mask] == y_true[mask])
    unc  = uncertainty[mask].mean()
    print(f"  {grp:>8}: acc={acc:.4f}  mean_uncertainty={unc:.4f}  n={mask.sum()}")

acc_male   = np.mean(y_pred_effnet[gender_labels=='Male']   == y_true[gender_labels=='Male'])
acc_female = np.mean(y_pred_effnet[gender_labels=='Female'] == y_true[gender_labels=='Female'])
gender_gap = abs(acc_male - acc_female)
print(f"\n  Gender accuracy gap: {gender_gap:.4f} ({gender_gap*100:.2f}%)")

#  Fairlearn MetricFrame — Age Group

print("FAIRLEARN — Age Group Analysis")


age_accs = {}
age_uncs = {}
for grp in ['18-40','41-60','61+']:
    mask = age_labels == grp
    acc  = np.mean(y_pred_effnet[mask] == y_true[mask])
    unc  = uncertainty[mask].mean()
    age_accs[grp] = acc
    age_uncs[grp] = unc
    print(f"  {grp:>8}: acc={acc:.4f}  mean_uncertainty={unc:.4f}  n={mask.sum()}")

age_gap = max(age_accs.values()) - min(age_accs.values())
print(f"\n  Age group accuracy gap: {age_gap:.4f} ({age_gap*100:.2f}%)")

#  Novel analysis: high-uncertainty + demographics

print("NOVEL: High-uncertainty predictions by demographic group")


high_unc_threshold = np.percentile(uncertainty, 80)  # top 20% uncertain
high_unc_mask = uncertainty >= high_unc_threshold

print(f"\n  High uncertainty threshold (80th percentile): {high_unc_threshold:.4f}")
print(f"  High uncertainty predictions: {high_unc_mask.sum()}")

print("\n  Gender distribution in high-uncertainty predictions:")
for grp in ['Male','Female']:
    total_grp   = (gender_labels==grp).sum()
    high_unc_grp = (high_unc_mask & (gender_labels==grp)).sum()
    pct = high_unc_grp / high_unc_mask.sum() * 100
    base_pct = total_grp / n * 100
    print(f"    {grp:>8}: {high_unc_grp}/{high_unc_mask.sum()} "
          f"({pct:.1f}% of uncertain) vs {base_pct:.1f}% of total")

print("\n  Age group distribution in high-uncertainty predictions:")
for grp in ['18-40','41-60','61+']:
    total_grp    = (age_labels==grp).sum()
    high_unc_grp = (high_unc_mask & (age_labels==grp)).sum()
    pct = high_unc_grp / high_unc_mask.sum() * 100
    base_pct = total_grp / n * 100
    print(f"    {grp:>8}: {high_unc_grp}/{high_unc_mask.sum()} "
          f"({pct:.1f}% of uncertain) vs {base_pct:.1f}% of total")

#  Save demographics to disk
np.save(f'{PRED_DIR}/gender_labels.npy',    gender)
np.save(f'{PRED_DIR}/age_group_labels.npy', age_group)

# Save metrics
fairness_metrics = {
    'note': 'Demographics are simulated based on epidemiological literature — '
            'no real patient metadata available in this public dataset.',
    'gender': {
        'male_acc':    float(acc_male),
        'female_acc':  float(acc_female),
        'gap':         float(gender_gap)
    },
    'age_group': {
        'acc_18_40': float(age_accs['18-40']),
        'acc_41_60': float(age_accs['41-60']),
        'acc_61_plus': float(age_accs['61+']),
        'gap': float(age_gap)
    },
    'high_uncertainty_threshold_percentile': 80,
    'high_uncertainty_threshold_value': float(high_unc_threshold)
}
with open(f'{METRICS_DIR}/fairness_metrics.json','w') as f:
    json.dump(fairness_metrics, f, indent=2)

print("\nFairness metrics saved.")
print(json.dumps(fairness_metrics, indent=2))

# AIF360 + Mitigation + Fairness Figures

!pip install -q aif360

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import json
import warnings
warnings.filterwarnings('ignore')

from aif360.datasets import BinaryLabelDataset
from aif360.metrics import BinaryLabelDatasetMetric, ClassificationMetric
from aif360.algorithms.preprocessing import Reweighing
import pandas as pd

#  Reload demographics
gender    = np.load(f'{PRED_DIR}/gender_labels.npy')
age_group = np.load(f'{PRED_DIR}/age_group_labels.npy')

#  AIF360 on Gender
print("="*55)
print("AIF360 — Disparate Impact Analysis (Gender)")
print("="*55)

# Binary: correct=1, incorrect=0
y_correct = (y_pred_effnet == y_true).astype(float)

# Build AIF360 dataset
df_gender = pd.DataFrame({
    'y_true':   y_correct,
    'gender':   gender,   # 0=Male(privileged), 1=Female(unprivileged)
})
df_pred = df_gender.copy()

aif_dataset = BinaryLabelDataset(
    df=df_gender,
    label_names=['y_true'],
    protected_attribute_names=['gender'],
    favorable_label=1.0,
    unfavorable_label=0.0
)

# Disparate impact before mitigation
metric_orig = BinaryLabelDatasetMetric(
    aif_dataset,
    unprivileged_groups=[{'gender': 1}],
    privileged_groups=[{'gender': 0}]
)

di_before = metric_orig.disparate_impact()
spd_before = metric_orig.statistical_parity_difference()

print(f"\nBEFORE Reweighing:")
print(f"  Disparate Impact Ratio:         {di_before:.4f}  (ideal=1.0, >0.8 acceptable)")
print(f"  Statistical Parity Difference:  {spd_before:.4f} (ideal=0.0)")
print(f"  Male accuracy:                  {np.mean(y_pred_effnet[gender==0]==y_true[gender==0]):.4f}")
print(f"  Female accuracy:                {np.mean(y_pred_effnet[gender==1]==y_true[gender==1]):.4f}")

# Apply Reweighing mitigation
RW = Reweighing(
    unprivileged_groups=[{'gender': 1}],
    privileged_groups=[{'gender': 0}]
)
aif_reweighed = RW.fit_transform(aif_dataset)
weights = aif_reweighed.instance_weights

# Simulate reweighed accuracy (weighted accuracy)
acc_male_rw   = np.average(
    y_pred_effnet[gender==0] == y_true[gender==0],
    weights=weights[gender==0]
)
acc_female_rw = np.average(
    y_pred_effnet[gender==1] == y_true[gender==1],
    weights=weights[gender==1]
)

# Build reweighed dataset metric
metric_rw = BinaryLabelDatasetMetric(
    aif_reweighed,
    unprivileged_groups=[{'gender': 1}],
    privileged_groups=[{'gender': 0}]
)
di_after  = metric_rw.disparate_impact()
spd_after = metric_rw.statistical_parity_difference()

print(f"\nAFTER Reweighing:")
print(f"  Disparate Impact Ratio:         {di_after:.4f}")
print(f"  Statistical Parity Difference:  {spd_after:.4f}")
print(f"  Male accuracy (weighted):       {acc_male_rw:.4f}")
print(f"  Female accuracy (weighted):     {acc_female_rw:.4f}")

# AIF360 on Age Group
print("\n" + "="*55)
print("AIF360 — Disparate Impact Analysis (Age Group)")
print("="*55)

# Binary age: privileged=18-40 (0), unprivileged=61+ (2)
# Focus on youngest vs oldest comparison
mask_young = age_group == 0
mask_old   = age_group == 2

acc_young = np.mean(y_pred_effnet[mask_young] == y_true[mask_young])
acc_old   = np.mean(y_pred_effnet[mask_old]   == y_true[mask_old])
di_age    = acc_old / acc_young if acc_young > 0 else 0

print(f"\n  18-40 accuracy: {acc_young:.4f}")
print(f"  61+   accuracy: {acc_old:.4f}")
print(f"  Disparate Impact (61+ vs 18-40): {di_age:.4f}  (>0.8 acceptable)")
print(f"  Gap: {abs(acc_young-acc_old)*100:.2f}%")

#  Visualization
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Plot 1: Gender accuracy before/after
groups   = ['Male', 'Female']
acc_bef  = [np.mean(y_pred_effnet[gender==0]==y_true[gender==0]),
            np.mean(y_pred_effnet[gender==1]==y_true[gender==1])]
acc_aft  = [acc_male_rw, acc_female_rw]
x = np.arange(2)
axes[0].bar(x-0.2, acc_bef, 0.35, label='Before Reweighing',
            color=['steelblue','steelblue'], alpha=0.8)
axes[0].bar(x+0.2, acc_aft, 0.35, label='After Reweighing',
            color=['coral','coral'], alpha=0.8)
axes[0].set_xticks(x); axes[0].set_xticklabels(groups)
axes[0].set_ylabel('Accuracy'); axes[0].set_ylim(0.85, 0.97)
axes[0].set_title('Gender — Before vs After Reweighing', fontsize=11)
axes[0].legend(fontsize=8); axes[0].grid(alpha=0.3, axis='y')
axes[0].axhline(y=np.mean(y_pred_effnet==y_true),
                color='gray', linestyle='--', alpha=0.6, label='Overall')

# Plot 2: Age group accuracy
age_groups_lbl = ['18-40', '41-60', '61+']
age_accs_vals  = [
    np.mean(y_pred_effnet[age_group==0]==y_true[age_group==0]),
    np.mean(y_pred_effnet[age_group==1]==y_true[age_group==1]),
    np.mean(y_pred_effnet[age_group==2]==y_true[age_group==2])
]
colors = ['steelblue', 'orange', 'coral']
axes[1].bar(age_groups_lbl, age_accs_vals, color=colors, alpha=0.8)
axes[1].set_ylabel('Accuracy'); axes[1].set_ylim(0.85, 0.97)
axes[1].set_title('Age Group Accuracy Disparity', fontsize=11)
axes[1].axhline(y=np.mean(y_pred_effnet==y_true),
                color='gray', linestyle='--', alpha=0.6, label='Overall avg')
axes[1].legend(fontsize=8); axes[1].grid(alpha=0.3, axis='y')
for i, v in enumerate(age_accs_vals):
    axes[1].text(i, v+0.001, f'{v:.3f}', ha='center', fontsize=9)

# Plot 3: Uncertainty by age group (novel finding)
age_uncs_vals = [
    uncertainty[age_group==0].mean(),
    uncertainty[age_group==1].mean(),
    uncertainty[age_group==2].mean()
]
axes[2].bar(age_groups_lbl, age_uncs_vals, color=colors, alpha=0.8)
axes[2].set_ylabel('Mean Uncertainty (MC Dropout std)')
axes[2].set_title('Mean Uncertainty by Age Group\n(Novel: Older = More Uncertain)',
                  fontsize=11)
axes[2].grid(alpha=0.3, axis='y')
for i, v in enumerate(age_uncs_vals):
    axes[2].text(i, v+0.0003, f'{v:.4f}', ha='center', fontsize=9)

plt.suptitle('Phase 4 — Fairness Audit: EfficientNetB3 Brain Tumor Classifier',
             fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig(f'{FIGURES_DIR}/fairness_audit.png', dpi=150, bbox_inches='tight')
plt.show()

# Save complete fairness report
fairness_report = {
    'disclaimer': 'Demographic labels are simulated based on epidemiological '
                  'literature due to absence of clinical metadata in this public dataset. '
                  'Results demonstrate the fairness audit methodology, not real-world disparities.',
    'gender_audit': {
        'disparate_impact_before': float(di_before),
        'disparate_impact_after':  float(di_after),
        'spd_before': float(spd_before),
        'spd_after':  float(spd_after),
        'male_acc':   float(acc_bef[0]),
        'female_acc': float(acc_bef[1]),
        'gap':        float(abs(acc_bef[0]-acc_bef[1])),
        'mitigation': 'Reweighing (AIF360)'
    },
    'age_audit': {
        'acc_18_40':  float(age_accs_vals[0]),
        'acc_41_60':  float(age_accs_vals[1]),
        'acc_61_plus':float(age_accs_vals[2]),
        'disparate_impact_61_vs_1840': float(di_age),
        'gap': float(abs(age_accs_vals[0]-age_accs_vals[2]))
    },
    'novel_finding': {
        'description': 'High-uncertainty predictions (top 20%) are disproportionately '
                       'concentrated in the 61+ age group (36.9% of uncertain vs 26.3% of total) '
                       'and Female patients (59.1% vs 53.2%), suggesting MC Dropout uncertainty '
                       'is a proxy for demographic underrepresentation.',
        'high_unc_threshold': 0.0445,
        'age_61plus_pct_uncertain': 36.9,
        'age_61plus_pct_total':     26.3,
        'female_pct_uncertain':     59.1,
        'female_pct_total':         53.2
    }
}

with open(f'{METRICS_DIR}/fairness_report_complete.json', 'w') as f:
    json.dump(fairness_report, f, indent=2)

print("\nFairness report saved.")
print("\n=== KEY FINDINGS ===")
print(f"Gender DI before: {di_before:.4f} → after: {di_after:.4f}")
print(f"Age gap: {abs(age_accs_vals[0]-age_accs_vals[2])*100:.2f}%")
print(f"Novel: 61+ over-represented in high-uncertainty by "
      f"{36.9-26.3:.1f} percentage points")

#  Equalized Odds + Demographic Parity

!pip install -q fairlearn

import numpy as np
import matplotlib.pyplot as plt
import json
import warnings
warnings.filterwarnings('ignore')

from fairlearn.metrics import (
    MetricFrame,
    equalized_odds_difference,
    demographic_parity_difference,
    false_negative_rate,
    selection_rate
)
from sklearn.metrics import accuracy_score

# Reload demographics
gender    = np.load(f'{PRED_DIR}/gender_labels.npy')
age_group = np.load(f'{PRED_DIR}/age_group_labels.npy')
gender_labels = np.array(['Male','Female'])[gender]
age_labels    = np.array(['18-40','41-60','61+'])[age_group]

print("="*55)
print("FAIRLEARN — Equalized Odds (per class, OvR)")
print("="*55)

eod_results = {}
dpd_results = {}

for cls_idx, cls_name in enumerate(CLASS_NAMES):
    y_bin      = (y_true == cls_idx).astype(int)
    y_pred_bin = (y_pred_effnet == cls_idx).astype(int)

    eod_gender = equalized_odds_difference(
        y_bin, y_pred_bin, sensitive_features=gender_labels)
    dpd_gender = demographic_parity_difference(
        y_bin, y_pred_bin, sensitive_features=gender_labels)
    eod_age = equalized_odds_difference(
        y_bin, y_pred_bin, sensitive_features=age_labels)
    dpd_age = demographic_parity_difference(
        y_bin, y_pred_bin, sensitive_features=age_labels)

    eod_results[cls_name] = {'gender': float(eod_gender), 'age': float(eod_age)}
    dpd_results[cls_name] = {'gender': float(dpd_gender), 'age': float(dpd_age)}

    print(f"\n  {cls_name.upper()}")
    print(f"    Equalized Odds Diff (gender): {eod_gender:.4f}  (ideal=0, <0.1 good)")
    print(f"    Equalized Odds Diff (age):    {eod_age:.4f}")
    print(f"    Demographic Parity Diff (gender): {dpd_gender:.4f}")
    print(f"    Demographic Parity Diff (age):    {dpd_age:.4f}")

# Visualization
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
x = np.arange(len(CLASS_NAMES))

eod_g = [eod_results[c]['gender'] for c in CLASS_NAMES]
eod_a = [eod_results[c]['age']    for c in CLASS_NAMES]
dpd_g = [dpd_results[c]['gender'] for c in CLASS_NAMES]
dpd_a = [dpd_results[c]['age']    for c in CLASS_NAMES]

axes[0].bar(x-0.2, eod_g, 0.35, label='Gender', color='steelblue', alpha=0.8)
axes[0].bar(x+0.2, eod_a, 0.35, label='Age',    color='coral',     alpha=0.8)
axes[0].axhline(y=0.1, color='red', linestyle='--', alpha=0.5, label='Threshold (0.1)')
axes[0].set_xticks(x)
axes[0].set_xticklabels([c.capitalize() for c in CLASS_NAMES])
axes[0].set_ylabel('Equalized Odds Difference')
axes[0].set_title('Equalized Odds Difference by Class', fontsize=11)
axes[0].legend(fontsize=9); axes[0].grid(alpha=0.3, axis='y')

axes[1].bar(x-0.2, dpd_g, 0.35, label='Gender', color='steelblue', alpha=0.8)
axes[1].bar(x+0.2, dpd_a, 0.35, label='Age',    color='coral',     alpha=0.8)
axes[1].axhline(y=0.05, color='red', linestyle='--', alpha=0.5, label='Threshold (0.05)')
axes[1].set_xticks(x)
axes[1].set_xticklabels([c.capitalize() for c in CLASS_NAMES])
axes[1].set_ylabel('Demographic Parity Difference')
axes[1].set_title('Demographic Parity Difference by Class', fontsize=11)
axes[1].legend(fontsize=9); axes[1].grid(alpha=0.3, axis='y')

plt.suptitle('Fairlearn — Equalized Odds & Demographic Parity', fontsize=13)
plt.tight_layout()
plt.savefig(f'{FIGURES_DIR}/equalized_odds.png', dpi=150, bbox_inches='tight')
plt.show()

fairness_eq = {
    'equalized_odds_difference': eod_results,
    'demographic_parity_difference': dpd_results
}
with open(f'{METRICS_DIR}/equalized_odds.json', 'w') as f:
    json.dump(fairness_eq, f, indent=2)

print("\nSaved.")
print(json.dumps(fairness_eq, indent=2))

# MRI Artifact Robustness Testing (Task 35)
# Gaussian blur x3, brightness shift, JPEG compression

import numpy as np
import matplotlib.pyplot as plt
import cv2, os, json
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

# Reload 4 test images + full test set labels
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
CLAHE_DIR    = f'{PROJECT_ROOT}/data/clahe_processed'
PRED_DIR     = f'{PROJECT_ROOT}/results/predictions'
METRICS_DIR  = f'{PROJECT_ROOT}/results/metrics'
FIGURES_DIR  = f'{PROJECT_ROOT}/results/figures'
CLASS_NAMES  = ['glioma', 'meningioma', 'notumor', 'pituitary']
IMG_SIZE     = (224, 224)
BATCH_SIZE   = 32

y_true        = np.load(f'{PRED_DIR}/y_true.npy')
y_pred_effnet = np.load(f'{PRED_DIR}/y_pred_effnet_final.npy')

effnet_model = tf.keras.models.load_model(
    f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2b.keras'
)

# Load full test set images for robustness testing
print("Loading test images for robustness testing...")
test_ds = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Testing',
    seed=42, image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=False
)

X_list, y_list = [], []
for x_batch, y_batch in test_ds:
    X_list.append(x_batch.numpy())
    y_list.append(y_batch.numpy())
X_test = np.concatenate(X_list, axis=0).astype(np.uint8)
y_check = np.concatenate(y_list, axis=0)
del X_list, y_list
print(f"Loaded: {X_test.shape}, labels match: {np.array_equal(y_check, y_true)}")

# Artifact functions
def apply_gaussian_blur(images, kernel_size):
    return np.array([cv2.GaussianBlur(img, (kernel_size, kernel_size), 0)
                     for img in images])

def apply_brightness_shift(images, delta):
    shifted = images.astype(np.int16) + delta
    return np.clip(shifted, 0, 255).astype(np.uint8)

def apply_jpeg_compression(images, quality):
    result = []
    for img in images:
        encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), quality]
        _, enc = cv2.imencode('.jpg', cv2.cvtColor(img, cv2.COLOR_RGB2BGR),
                              encode_param)
        dec = cv2.imdecode(enc, cv2.IMREAD_COLOR)
        result.append(cv2.cvtColor(dec, cv2.COLOR_BGR2RGB))
    return np.array(result)

def predict_accuracy(images):
    preprocessed = tf.keras.applications.efficientnet.preprocess_input(
        images.astype(np.float32)
    )
    preds = []
    for i in range(0, len(preprocessed), BATCH_SIZE):
        batch = tf.constant(preprocessed[i:i+BATCH_SIZE])
        pred  = effnet_model(batch, training=False).numpy()
        preds.append(np.argmax(pred, axis=1))
    preds = np.concatenate(preds)
    return float(np.mean(preds == y_true))

#  Run robustness tests
print("\nRunning robustness tests...")
baseline_acc = float(np.mean(y_pred_effnet == y_true))
results = {'baseline': baseline_acc}

# Gaussian blur (3 levels)
print("  Gaussian blur...")
for k in [3, 7, 15]:
    blurred = apply_gaussian_blur(X_test, k)
    acc = predict_accuracy(blurred)
    results[f'gaussian_blur_k{k}'] = acc
    print(f"    kernel={k}: {acc:.4f}")

# Brightness shift (3 levels)
print("  Brightness shift...")
for delta in [-50, +50, +80]:
    shifted = apply_brightness_shift(X_test, delta)
    acc = predict_accuracy(shifted)
    label = f'brightness_{"+"+str(delta) if delta>0 else str(delta)}'
    results[label] = acc
    print(f"    delta={delta:+d}: {acc:.4f}")

# JPEG compression (3 quality levels)
print("  JPEG compression...")
for q in [80, 50, 20]:
    compressed = apply_jpeg_compression(X_test, q)
    acc = predict_accuracy(compressed)
    results[f'jpeg_q{q}'] = acc
    print(f"    quality={q}: {acc:.4f}")

print("\nAll robustness tests complete.")

#  Visualization
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Gaussian blur
blur_ks   = [3, 7, 15]
blur_accs = [results[f'gaussian_blur_k{k}'] for k in blur_ks]
axes[0].plot(blur_ks, blur_accs, 'o-', color='steelblue', linewidth=2, markersize=8)
axes[0].axhline(y=baseline_acc, color='gray', linestyle='--', label=f'Baseline ({baseline_acc:.3f})')
axes[0].set_xlabel('Gaussian Kernel Size')
axes[0].set_ylabel('Accuracy')
axes[0].set_title('Robustness — Gaussian Blur', fontsize=11)
axes[0].legend(fontsize=9); axes[0].grid(alpha=0.3)
axes[0].set_ylim(0.7, 1.0)
for k, acc in zip(blur_ks, blur_accs):
    axes[0].annotate(f'{acc:.3f}', (k, acc), textcoords="offset points",
                     xytext=(0,8), ha='center', fontsize=9)

# Brightness shift
br_deltas = [-50, 50, 80]
br_accs   = [results[f'brightness_{"+"+str(d) if d>0 else str(d)}'] for d in br_deltas]
axes[1].bar([str(d) for d in br_deltas], br_accs,
            color=['coral','steelblue','orange'], alpha=0.8)
axes[1].axhline(y=baseline_acc, color='gray', linestyle='--', label=f'Baseline ({baseline_acc:.3f})')
axes[1].set_xlabel('Brightness Delta')
axes[1].set_ylabel('Accuracy')
axes[1].set_title('Robustness — Brightness Shift', fontsize=11)
axes[1].legend(fontsize=9); axes[1].grid(alpha=0.3, axis='y')
axes[1].set_ylim(0.7, 1.0)
for i, acc in enumerate(br_accs):
    axes[1].text(i, acc+0.005, f'{acc:.3f}', ha='center', fontsize=9)

# JPEG compression
jpeg_qs   = [80, 50, 20]
jpeg_accs = [results[f'jpeg_q{q}'] for q in jpeg_qs]
axes[2].plot(jpeg_qs, jpeg_accs, 's-', color='coral', linewidth=2, markersize=8)
axes[2].axhline(y=baseline_acc, color='gray', linestyle='--', label=f'Baseline ({baseline_acc:.3f})')
axes[2].set_xlabel('JPEG Quality')
axes[2].set_ylabel('Accuracy')
axes[2].set_title('Robustness — JPEG Compression', fontsize=11)
axes[2].legend(fontsize=9); axes[2].grid(alpha=0.3)
axes[2].set_ylim(0.7, 1.0)
axes[2].invert_xaxis()
for q, acc in zip(jpeg_qs, jpeg_accs):
    axes[2].annotate(f'{acc:.3f}', (q, acc), textcoords="offset points",
                     xytext=(0,8), ha='center', fontsize=9)

plt.suptitle('MRI Artifact Robustness — EfficientNetB3', fontsize=13)
plt.tight_layout()
plt.savefig(f'{FIGURES_DIR}/artifact_robustness.png', dpi=150, bbox_inches='tight')
plt.show()

# Save
with open(f'{METRICS_DIR}/artifact_robustness.json', 'w') as f:
    json.dump(results, f, indent=2)

print("\nRobustness results saved.")
print(json.dumps(results, indent=2))

# Experiment 8: Real Motion-Artifact + Gaussian Noise Simulation
# Extends the existing Artifact Robustness section (Gaussian blur, brightness, JPEG)
# with (a) directional motion blur (simulates patient movement during scan) and
# (b) additive Gaussian sensor noise (distinct from Gaussian *blur* already tested).

import numpy as np
import matplotlib.pyplot as plt
import cv2, os, json
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'  # CPU-only, inference is cheap

PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
CLAHE_DIR    = f'{PROJECT_ROOT}/data/clahe_processed'
PRED_DIR     = f'{PROJECT_ROOT}/results/predictions'
METRICS_DIR  = f'{PROJECT_ROOT}/results/metrics'
FIGURES_DIR  = f'{PROJECT_ROOT}/results/figures'
CLASS_NAMES  = ['glioma', 'meningioma', 'notumor', 'pituitary']
IMG_SIZE     = (224, 224)
BATCH_SIZE   = 32

y_true        = np.load(f'{PRED_DIR}/y_true.npy')
y_pred_effnet = np.load(f'{PRED_DIR}/y_pred_effnet_final.npy')

effnet_model = tf.keras.models.load_model(
    f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2b.keras'
)

print("Loading test images...")
test_ds = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Testing',
    seed=42, image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=False
)
X_list, y_list = [], []
for x_batch, y_batch in test_ds:
    X_list.append(x_batch.numpy())
    y_list.append(y_batch.numpy())
X_test  = np.concatenate(X_list, axis=0).astype(np.uint8)
y_check = np.concatenate(y_list, axis=0)
del X_list, y_list
print(f"Loaded: {X_test.shape}, labels match: {np.array_equal(y_check, y_true)}")

# --- Directional motion blur (simulates patient head movement during acquisition) ---
def apply_motion_blur(images, kernel_size, angle_deg=0):
    """Linear motion blur kernel at a given length and angle."""
    kernel = np.zeros((kernel_size, kernel_size))
    kernel[kernel_size // 2, :] = 1.0
    center = (kernel_size / 2 - 0.5, kernel_size / 2 - 0.5)
    rot_mat = cv2.getRotationMatrix2D(center, angle_deg, 1.0)
    kernel = cv2.warpAffine(kernel, rot_mat, (kernel_size, kernel_size))
    kernel = kernel / kernel.sum()
    return np.array([cv2.filter2D(img, -1, kernel) for img in images])

# --- Additive Gaussian sensor noise (distinct from Gaussian *blur*) ---
def apply_gaussian_noise(images, sigma):
    noisy = images.astype(np.float32) + np.random.normal(0, sigma, images.shape)
    return np.clip(noisy, 0, 255).astype(np.uint8)

def predict_accuracy(images):
    preprocessed = tf.keras.applications.efficientnet.preprocess_input(
        images.astype(np.float32)
    )
    preds = []
    for i in range(0, len(preprocessed), BATCH_SIZE):
        batch = tf.constant(preprocessed[i:i+BATCH_SIZE])
        pred  = effnet_model(batch, training=False).numpy()
        preds.append(np.argmax(pred, axis=1))
    preds = np.concatenate(preds)
    return float(np.mean(preds == y_true))

baseline_acc = float(np.mean(y_pred_effnet == y_true))
results = {'baseline': baseline_acc}

print("\nRunning motion-blur sweep...")
motion_lengths = [5, 9, 15]
for length in motion_lengths:
    blurred = apply_motion_blur(X_test, length, angle_deg=30)  # 30° = plausible head-tilt motion
    acc = predict_accuracy(blurred)
    results[f'motion_blur_len{length}'] = acc
    print(f"  length={length}px: {acc:.4f}")

print("\nRunning Gaussian noise sweep...")
noise_sigmas = [5, 15, 25]
for sigma in noise_sigmas:
    noisy = apply_gaussian_noise(X_test, sigma)
    acc = predict_accuracy(noisy)
    results[f'gaussian_noise_sigma{sigma}'] = acc
    print(f"  sigma={sigma}: {acc:.4f}")

print("\nAll Experiment 8 tests complete.")

# --- Visualization ---
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

mb_accs = [results[f'motion_blur_len{l}'] for l in motion_lengths]
axes[0].plot(motion_lengths, mb_accs, 'o-', color='steelblue', linewidth=2, markersize=8)
axes[0].axhline(y=baseline_acc, color='gray', linestyle='--', label=f'Baseline ({baseline_acc:.3f})')
axes[0].set_xlabel('Motion Blur Length (px)')
axes[0].set_ylabel('Accuracy')
axes[0].set_title('Robustness — Directional Motion Blur', fontsize=11)
axes[0].legend(fontsize=9); axes[0].grid(alpha=0.3)
axes[0].set_ylim(0.0, 1.0)
for l, acc in zip(motion_lengths, mb_accs):
    axes[0].annotate(f'{acc:.3f}', (l, acc), textcoords="offset points", xytext=(0,8), ha='center', fontsize=9)

gn_accs = [results[f'gaussian_noise_sigma{s}'] for s in noise_sigmas]
axes[1].plot(noise_sigmas, gn_accs, 's-', color='coral', linewidth=2, markersize=8)
axes[1].axhline(y=baseline_acc, color='gray', linestyle='--', label=f'Baseline ({baseline_acc:.3f})')
axes[1].set_xlabel('Gaussian Noise σ')
axes[1].set_ylabel('Accuracy')
axes[1].set_title('Robustness — Additive Gaussian Noise', fontsize=11)
axes[1].legend(fontsize=9); axes[1].grid(alpha=0.3)
axes[1].set_ylim(0.0, 1.0)
for s, acc in zip(noise_sigmas, gn_accs):
    axes[1].annotate(f'{acc:.3f}', (s, acc), textcoords="offset points", xytext=(0,8), ha='center', fontsize=9)

plt.suptitle('MRI Robustness — Motion Blur & Sensor Noise (Experiment 8)', fontsize=13)
plt.tight_layout()
plt.savefig(f'{FIGURES_DIR}/motion_noise_robustness.png', dpi=150, bbox_inches='tight')
plt.show()

with open(f'{METRICS_DIR}/motion_noise_robustness.json', 'w') as f:
    json.dump(results, f, indent=2)

print("\nSaved.")
print(json.dumps(results, indent=2))