# -*- coding: utf-8 -*-
"""MRI_1_setup_baseline_efficientnet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xIwh96dLBeSmekBJe8V5ek6lTkNtjYF
"""

#  Reproducible environment + fixed seeds


# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Set fixed seeds for full reproducibility
import os
import random
import numpy as np
import tensorflow as tf

SEED = 42
os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))
print("Seeds fixed at:", SEED)

# 3. Create project folder structure on Drive
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'

folders = [
    PROJECT_ROOT,
    f'{PROJECT_ROOT}/data',
    f'{PROJECT_ROOT}/data/raw',
    f'{PROJECT_ROOT}/data/processed',
    f'{PROJECT_ROOT}/models',
    f'{PROJECT_ROOT}/models/checkpoints',
    f'{PROJECT_ROOT}/results',
    f'{PROJECT_ROOT}/results/figures',
    f'{PROJECT_ROOT}/results/metrics',
    f'{PROJECT_ROOT}/results/predictions',
    f'{PROJECT_ROOT}/notebooks',
    f'{PROJECT_ROOT}/logs',
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("\nProject structure created at:", PROJECT_ROOT)
for f in folders:
    print(" -", f.replace(PROJECT_ROOT, '.'))

import tensorflow as tf
import numpy as np
import gc, json

# Define global variables needed for this cell
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
CLAHE_DIR    = f'{PROJECT_ROOT}/data/clahe_processed'
PRED_DIR     = f'{PROJECT_ROOT}/results/predictions'
METRICS_DIR  = f'{PROJECT_ROOT}/results/metrics'
CLASS_NAMES  = ['glioma', 'meningioma', 'notumor', 'pituitary']
IMG_SIZE     = (224, 224)
BATCH_SIZE   = 32

# Load y_true once for evaluation
y_true = np.load(f'{PRED_DIR}/y_true.npy')


# Retrain remaining 4 baseline models on the CLEAN split — MobileNetV2, ResNet50, InceptionV3, VGG16
# Same protocol as EfficientNetB3: Stage 1 (frozen, 10 epochs) + Stage 2 (unfrozen last 30, 15 epochs)

models_to_train = {
    'MobileNetV2': tf.keras.applications.MobileNetV2,
    'ResNet50':    tf.keras.applications.ResNet50,
    'InceptionV3': tf.keras.applications.InceptionV3,
    'VGG16':       tf.keras.applications.VGG16,
}

# InceptionV3 needs larger input size; others fine at 224x224
input_sizes = {
    'MobileNetV2': (224,224), 'ResNet50': (224,224),
    'InceptionV3': (299,299), 'VGG16': (224,224)
}
preprocess_fns = {
    'MobileNetV2': tf.keras.applications.mobilenet_v2.preprocess_input,
    'ResNet50':    tf.keras.applications.resnet50.preprocess_input,
    'InceptionV3': tf.keras.applications.inception_v3.preprocess_input,
    'VGG16':       tf.keras.applications.vgg16.preprocess_input,
}

clean_results = {}

for name, ModelClass in models_to_train.items():
    print(f"\n{'='*55}\n{name}\n{'='*55}")
    tf.keras.backend.clear_session()
    gc.collect()

    img_size = input_sizes[name]
    preprocess_fn = preprocess_fns[name]

    # Rebuild train/val/test datasets at this model's required input size
    def prep(ds_dir, split, subset=None, val_split=None, shuffle=True):
        kwargs = dict(seed=42, image_size=img_size, batch_size=BATCH_SIZE,
                      label_mode='int', class_names=CLASS_NAMES, shuffle=shuffle)
        if val_split:
            kwargs.update(validation_split=val_split, subset=subset)
        raw = tf.keras.utils.image_dataset_from_directory(f'{ds_dir}/{split}', **kwargs)
        return raw.map(lambda x,y: (preprocess_fn(x), y), num_parallel_calls=tf.data.AUTOTUNE).prefetch(tf.data.AUTOTUNE)

    train_ds_m = prep(CLAHE_DIR, 'Training', subset='training', val_split=0.1)
    val_ds_m   = prep(CLAHE_DIR, 'Training', subset='validation', val_split=0.1)
    test_ds_m  = prep(CLAHE_DIR, 'Testing', shuffle=False)

    base = ModelClass(include_top=False, weights='imagenet', input_shape=(*img_size,3))
    base.trainable = False
    inputs = tf.keras.layers.Input(shape=(*img_size,3))
    x = base(inputs, training=False)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    outputs = tf.keras.layers.Dense(len(CLASS_NAMES), activation='softmax')(x)
    model = tf.keras.Model(inputs, outputs)

    # Stage 1: frozen
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                  loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    model.fit(train_ds_m, validation_data=val_ds_m, epochs=10,
              callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)],
              verbose=1)

    # Stage 2: unfreeze last 30 layers
    base.trainable = True
    for layer in base.layers[:-30]:
        layer.trainable = False
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-5),
                  loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    model.fit(train_ds_m, validation_data=val_ds_m, epochs=15,
              callbacks=[
                  tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True),
                  tf.keras.callbacks.ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=2)
              ], verbose=1)

    # Evaluate on fixed test set
    y_pred_probs_m = model.predict(test_ds_m, verbose=0)
    y_pred_m = np.argmax(y_pred_probs_m, axis=1)
    acc = float(np.mean(y_pred_m == y_true))
    f1  = float(tf.keras.metrics.F1Score(average='weighted')(
        tf.one_hot(y_true, len(CLASS_NAMES)), y_pred_probs_m).numpy())
    params = model.count_params() / 1e6

    clean_results[name] = {'accuracy': acc, 'f1_weighted': f1, 'params_M': params}
    print(f"\n{name} clean results: acc={acc:.4f}, F1={f1:.4f}, params={params:.2f}M")

    model.save(f'{PROJECT_ROOT}/models/checkpoints/{name.lower()}_clean.keras')
    del model, base, train_ds_m, val_ds_m, test_ds_m
    tf.keras.backend.clear_session()
    gc.collect()

print("\n" + "="*55)
print("ALL MODELS RETRAINED — CLEAN SPLIT RESULTS")
print("="*55)
for name, r in clean_results.items():
    print(f"  {name}: acc={r['accuracy']:.4f}, F1={r['f1_weighted']:.4f}, params={r['params_M']:.2f}M")

with open(f'{METRICS_DIR}/baseline_models_clean.json', 'w') as f:
    json.dump(clean_results, f, indent=2)
print("\nSaved.")

import tensorflow as tf
import numpy as np
import gc, json, os

# Force CPU-only execution (must be set before any TF ops run in this session)
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
tf.config.set_visible_devices([], 'GPU')

# Define global variables needed for this cell
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
CLAHE_DIR    = f'{PROJECT_ROOT}/data/clahe_processed'
PRED_DIR     = f'{PROJECT_ROOT}/results/predictions'
METRICS_DIR  = f'{PROJECT_ROOT}/results/metrics'
CLASS_NAMES  = ['glioma', 'meningioma', 'notumor', 'pituitary']
BATCH_SIZE   = 32

# Load y_true once for evaluation
y_true = np.load(f'{PRED_DIR}/y_true.npy')

name = 'VGG16'
ModelClass    = tf.keras.applications.VGG16
img_size      = (224, 224)
preprocess_fn = tf.keras.applications.vgg16.preprocess_input

print(f"\n{'='*55}\n{name} (CPU)\n{'='*55}")
tf.keras.backend.clear_session()
gc.collect()

def prep(ds_dir, split, subset=None, val_split=None, shuffle=True):
    kwargs = dict(seed=42, image_size=img_size, batch_size=BATCH_SIZE,
                  label_mode='int', class_names=CLASS_NAMES, shuffle=shuffle)
    if val_split:
        kwargs.update(validation_split=val_split, subset=subset)
    raw = tf.keras.utils.image_dataset_from_directory(f'{ds_dir}/{split}', **kwargs)
    return raw.map(lambda x, y: (preprocess_fn(x), y), num_parallel_calls=tf.data.AUTOTUNE).prefetch(tf.data.AUTOTUNE)

with tf.device('/CPU:0'):
    train_ds_m = prep(CLAHE_DIR, 'Training', subset='training', val_split=0.1)
    val_ds_m   = prep(CLAHE_DIR, 'Training', subset='validation', val_split=0.1)
    test_ds_m  = prep(CLAHE_DIR, 'Testing', shuffle=False)

    base = ModelClass(include_top=False, weights='imagenet', input_shape=(*img_size, 3))
    base.trainable = False
    inputs = tf.keras.layers.Input(shape=(*img_size, 3))
    x = base(inputs, training=False)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    outputs = tf.keras.layers.Dense(len(CLASS_NAMES), activation='softmax')(x)
    model = tf.keras.Model(inputs, outputs)

    # Stage 1: frozen
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                  loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    model.fit(train_ds_m, validation_data=val_ds_m, epochs=10,
              callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)],
              verbose=1)

    # Stage 2: unfreeze last 30 layers
    base.trainable = True
    for layer in base.layers[:-30]:
        layer.trainable = False
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-5),
                  loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    model.fit(train_ds_m, validation_data=val_ds_m, epochs=15,
              callbacks=[
                  tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True),
                  tf.keras.callbacks.ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=2)
              ], verbose=1)

    # Evaluate on fixed test set
    y_pred_probs_m = model.predict(test_ds_m, verbose=0)

y_pred_m = np.argmax(y_pred_probs_m, axis=1)
acc = float(np.mean(y_pred_m == y_true))
f1  = float(tf.keras.metrics.F1Score(average='weighted')(
    tf.one_hot(y_true, len(CLASS_NAMES)), y_pred_probs_m).numpy())
params = model.count_params() / 1e6

clean_results = {name: {'accuracy': acc, 'f1_weighted': f1, 'params_M': params}}
print(f"\n{name} clean results: acc={acc:.4f}, F1={f1:.4f}, params={params:.2f}M")

model.save(f'{PROJECT_ROOT}/models/checkpoints/{name.lower()}_clean.keras')
del model, base, train_ds_m, val_ds_m, test_ds_m
tf.keras.backend.clear_session()
gc.collect()

with open(f'{METRICS_DIR}/baseline_models_clean.json', 'w') as f:
    json.dump(clean_results, f, indent=2)
print("\nSaved.")

# 1.requirements.txt
requirements_content = """tensorflow==2.20.0
opencv-python-headless==4.10.0.84
numpy==1.26.4
pandas==2.2.2
scikit-learn==1.5.2
matplotlib==3.9.2
seaborn==0.13.2
scipy==1.13.1
statsmodels==0.14.2
grad-cam==1.5.4
lime==0.2.0.1
shap==0.46.0
fairlearn==0.11.0
aif360==0.6.1
gradio==4.44.0
netcal==1.3.5
SimpleITK==2.4.0
huggingface_hub==0.25.1
kagglehub==0.3.3
"""

PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
with open(f'{PROJECT_ROOT}/requirements.txt', 'w') as f:
    f.write(requirements_content)

print("requirements.txt written to Drive.")
print(requirements_content)

# 2. Install the packages not already in Colab by default
!pip install -q opencv-python-headless==4.10.0.84 grad-cam==1.5.4 lime==0.2.0.1 \
    shap==0.46.0 fairlearn==0.11.0 aif360==0.6.1 gradio==4.44.0 netcal==1.3.5 \
    SimpleITK==2.4.0 statsmodels==0.14.2 kagglehub==0.3.3

print("\nAll packages installed.")

# Download Brain Tumor MRI Dataset

import kagglehub

# Downloads Masoud Nickparvar's Brain Tumor MRI Dataset
# (glioma, meningioma, pituitary, notumor - pre-split train/test)
dataset_path = kagglehub.dataset_download("masoudnickparvar/brain-tumor-mri-dataset")
print("Dataset downloaded to:", dataset_path)

# Inspect structure
import os
for root, dirs, files in os.walk(dataset_path):
    level = root.replace(dataset_path, '').count(os.sep)
    indent = ' ' * 2 * level
    print(f'{indent}{os.path.basename(root)}/')
    if level >= 2:
        print(f'{indent}  ... ({len(files)} files)')
        dirs[:] = []  # don't descend further

# Copy dataset into our Drive project folder
import shutil

PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
DATA_DEST = f'{PROJECT_ROOT}/data/raw'

if not os.path.exists(f'{DATA_DEST}/Training'):
    print("Copying dataset to Drive (this may take a few minutes)...")
    shutil.copytree(dataset_path, DATA_DEST, dirs_exist_ok=True)
    print("Copy complete.")
else:
    print("Dataset already exists in Drive, skipping copy.")

# Verify
for split in ['Training', 'Testing']:
    split_path = f'{DATA_DEST}/{split}'
    if os.path.exists(split_path):
        classes = os.listdir(split_path)
        print(f"\n{split}:")
        for c in classes:
            n = len(os.listdir(f'{split_path}/{c}'))
            print(f"  {c}: {n} images")

import tensorflow as tf

PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
DATA_DIR = f'{PROJECT_ROOT}/data/raw'

IMG_SIZE = (224, 224)   # standard size, works for both scratch CNN and EfficientNetB3 later
BATCH_SIZE = 32
SEED = 42

CLASS_NAMES = ['glioma', 'meningioma', 'notumor', 'pituitary']  # alphabetical, fixed order

# Training set -> split into train (90%) / val (10%), stratified by keras automatically via seed
train_ds = tf.keras.utils.image_dataset_from_directory(
    f'{DATA_DIR}/Training',
    validation_split=0.1,
    subset='training',
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='int',
    class_names=CLASS_NAMES,
    shuffle=True
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    f'{DATA_DIR}/Training',
    validation_split=0.1,
    subset='validation',
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='int',
    class_names=CLASS_NAMES,
    shuffle=True
)

# Held-out test set
test_ds = tf.keras.utils.image_dataset_from_directory(
    f'{DATA_DIR}/Testing',
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='int',
    class_names=CLASS_NAMES,
    shuffle=False   #  keep order fixed so predictions align with labels for McNemar later
)

print("Class names (fixed order):", CLASS_NAMES)
print("Train batches:", tf.data.experimental.cardinality(train_ds).numpy())
print("Val batches:", tf.data.experimental.cardinality(val_ds).numpy())
print("Test batches:", tf.data.experimental.cardinality(test_ds).numpy())

# Normalize pixel values to [0,1] and cache/prefetch for speed
normalization_layer = tf.keras.layers.Rescaling(1./255)

def prep(ds, training=False):
    ds = ds.map(lambda x, y: (normalization_layer(x), y), num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds = ds.cache().shuffle(1000, seed=SEED).prefetch(tf.data.AUTOTUNE)
    else:
        ds = ds.cache().prefetch(tf.data.AUTOTUNE)
    return ds

train_ds_norm = prep(train_ds, training=True)
val_ds_norm = prep(val_ds, training=False)
test_ds_norm = prep(test_ds, training=False)

print("\nData pipeline ready.")

# Scratch CNN baseline model

from tensorflow.keras import layers, models

tf.random.set_seed(SEED)  # re-fix seed right before model creation

def build_scratch_cnn(input_shape=(224,224,3), num_classes=4):
    model = models.Sequential([
        layers.Input(shape=input_shape),

        layers.Conv2D(16, 3, activation='relu', padding='same'),
        layers.MaxPooling2D(),

        layers.Conv2D(32, 3, activation='relu', padding='same'),
        layers.MaxPooling2D(),

        layers.Conv2D(64, 3, activation='relu', padding='same'),
        layers.MaxPooling2D(),

        layers.Conv2D(64, 3, activation='relu', padding='same'),
        layers.MaxPooling2D(),

        layers.Flatten(),
        layers.Dense(64, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation='softmax')
    ], name='scratch_cnn_baseline')
    return model

scratch_model = build_scratch_cnn()
scratch_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
scratch_model.summary()

print("\nTotal params:", scratch_model.count_params())

# Train the baseline
EPOCHS_BASELINE = 20

checkpoint_path = f'{PROJECT_ROOT}/models/checkpoints/scratch_cnn_baseline.keras'

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(
        checkpoint_path, save_best_only=True, monitor='val_accuracy', mode='max'
    ),
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy', patience=5, restore_best_weights=True
    )
]

history_baseline = scratch_model.fit(
    train_ds_norm,
    validation_data=val_ds_norm,
    epochs=EPOCHS_BASELINE,
    callbacks=callbacks
)

print("\nBaseline training complete. Best model saved to:", checkpoint_path)

import numpy as np
import tensorflow as tf

# Ensure PROJECT_ROOT is defined (it should be from previous cells, but good practice for standalone execution)
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'

# Define checkpoint_path, which was defined in a prior cell
checkpoint_path = f'{PROJECT_ROOT}/models/checkpoints/scratch_cnn_baseline.keras'

# Reload best checkpoint explicitly ( ensures we use saved best weights)
best_scratch_model = tf.keras.models.load_model(checkpoint_path)

# Get true labels in fixed test order
y_true = np.concatenate([y.numpy() for x, y in test_ds_norm], axis=0)

# Predict probabilities and classes
y_pred_probs_baseline = best_scratch_model.predict(test_ds_norm, verbose=1)
y_pred_baseline = np.argmax(y_pred_probs_baseline, axis=1)

# Final test accuracy
test_acc_baseline = np.mean(y_pred_baseline == y_true)
print(f"\nScratch CNN baseline TEST accuracy: {test_acc_baseline:.4f}")

# Save everything needed for later phases
PRED_DIR = f'{PROJECT_ROOT}/results/predictions'
np.save(f'{PRED_DIR}/y_true.npy', y_true)
np.save(f'{PRED_DIR}/y_pred_baseline.npy', y_pred_baseline)
np.save(f'{PRED_DIR}/y_pred_probs_baseline.npy', y_pred_probs_baseline)

# Save a small metrics log
import json
baseline_metrics = {
    'model': 'scratch_cnn_baseline',
    'params': int(best_scratch_model.count_params()),
    'test_accuracy': float(test_acc_baseline),
    'seed': SEED,
    'class_names': CLASS_NAMES
}
with open(f'{PROJECT_ROOT}/results/metrics/baseline_metrics.json', 'w') as f:
    json.dump(baseline_metrics, f, indent=2)

print("\nSaved to:", PRED_DIR)
print(json.dumps(baseline_metrics, indent=2))

#  CLAHE preprocessing

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# Definitions from earlier setup cells
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
DATA_DIR = f'{PROJECT_ROOT}/data/raw'
IMG_SIZE = (224, 224)
CLASS_NAMES = ['glioma', 'meningioma', 'notumor', 'pituitary']

def apply_clahe(image, clip_limit=2.0, tile_grid_size=(8, 8)):
    """
    Apply CLAHE (Contrast Limited Adaptive Histogram Equalization)
    to an MRI slice. Expects uint8 image, RGB or grayscale.
    """
    if image.dtype != np.uint8:
        image = (image * 255).astype(np.uint8) if image.max() <= 1.0 else image.astype(np.uint8)

    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=tile_grid_size)

    if len(image.shape) == 3 and image.shape[-1] == 3:
        # Apply CLAHE on the L channel in LAB space to preserve color balance
        lab = cv2.cvtColor(image, cv2.COLOR_RGB2LAB)
        l, a, b = cv2.split(lab)
        l_clahe = clahe.apply(l)
        lab_clahe = cv2.merge((l_clahe, a, b))
        result = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2RGB)
    else:
        result = clahe.apply(image)

    return result

# Quick visual sanity check on a few real MRI slices before applying to the whole dataset
sample_paths = []
for c in CLASS_NAMES:
    class_dir = f'{DATA_DIR}/Training/{c}'
    files_in_class = os.listdir(class_dir)[:1]
    sample_paths.append(f'{class_dir}/{files_in_class[0]}')

fig, axes = plt.subplots(2, 4, figsize=(16, 8))
for i, path in enumerate(sample_paths):
    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, IMG_SIZE)
    img_clahe = apply_clahe(img)

    axes[0, i].imshow(img)
    axes[0, i].set_title(f'{CLASS_NAMES[i]} - Original')
    axes[0, i].axis('off')

    axes[1, i].imshow(img_clahe)
    axes[1, i].set_title(f'{CLASS_NAMES[i]} - CLAHE')
    axes[1, i].axis('off')

plt.tight_layout()
plt.savefig(f'{PROJECT_ROOT}/results/figures/clahe_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

print("CLAHE comparison saved to results/figures/clahe_comparison.png")

# Apply CLAHE to the ENTIRE dataset (Training + Testing) and save to disk
import cv2, os, numpy as np
from pathlib import Path

DATA_DIR   = f'{PROJECT_ROOT}/data/raw'
CLAHE_DIR  = f'{PROJECT_ROOT}/data/clahe_processed'
CLASS_NAMES = ['glioma', 'meningioma', 'notumor', 'pituitary']

def apply_clahe(image, clip_limit=2.0, tile_grid_size=(8, 8)):
    if image.dtype != np.uint8:
        image = (image * 255).astype(np.uint8) if image.max() <= 1.0 else image.astype(np.uint8)
    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=tile_grid_size)
    if len(image.shape) == 3 and image.shape[-1] == 3:
        lab = cv2.cvtColor(image, cv2.COLOR_RGB2LAB)
        l, a, b = cv2.split(lab)
        l_clahe = clahe.apply(l)
        result = cv2.cvtColor(cv2.merge((l_clahe, a, b)), cv2.COLOR_LAB2RGB)
    else:
        result = clahe.apply(image)
    return result

for split in ['Training', 'Testing']:
    for c in CLASS_NAMES:
        src_dir = f'{DATA_DIR}/{split}/{c}'
        dst_dir = f'{CLAHE_DIR}/{split}/{c}'
        os.makedirs(dst_dir, exist_ok=True)
        files = os.listdir(src_dir)
        for i, fname in enumerate(files):
            dst_path = f'{dst_dir}/{fname}'
            if os.path.exists(dst_path):
                continue  # resume-safe, skip already-processed
            img = cv2.imread(f'{src_dir}/{fname}')
            if img is None:
                continue
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, IMG_SIZE)
            img_clahe = apply_clahe(img)
            cv2.imwrite(dst_path, cv2.cvtColor(img_clahe, cv2.COLOR_RGB2BGR))
        print(f"{split}/{c}: {len(files)} images processed -> {dst_dir}")

print("\nFull CLAHE dataset saved to:", CLAHE_DIR)

import tensorflow as tf

CLAHE_DIR   = f'{PROJECT_ROOT}/data/clahe_processed'
CLASS_NAMES = ['glioma', 'meningioma', 'notumor', 'pituitary']
SEED = 42

# Train (90%) / Val (10%) — both from Training/ only. Testing/ is untouched until final eval.
train_ds_raw = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Training',
    validation_split=0.1, subset='training', seed=SEED,
    image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=True
)
val_ds_raw = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Training',
    validation_split=0.1, subset='validation', seed=SEED,
    image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=True
)
test_ds_raw = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Testing',
    seed=SEED, image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=False
)

preprocess = tf.keras.applications.efficientnet.preprocess_input

def prep(ds, augment=False, training=False):
    ds = ds.map(lambda x, y: (preprocess(x), y), num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds = ds.cache().shuffle(1000, seed=SEED).prefetch(tf.data.AUTOTUNE)
    else:
        ds = ds.cache().prefetch(tf.data.AUTOTUNE)
    return ds

train_ds = prep(train_ds_raw, training=True)
val_ds   = prep(val_ds_raw,   training=False)
test_ds  = prep(test_ds_raw,  training=False)   # touched only at final eval

print("Train batches:", tf.data.experimental.cardinality(train_ds).numpy())
print("Val batches:  ", tf.data.experimental.cardinality(val_ds).numpy())
print("Test batches: ", tf.data.experimental.cardinality(test_ds).numpy())

from tensorflow.keras import layers, models, applications

tf.random.set_seed(SEED)

def build_effnet(num_classes=4):
    base = applications.EfficientNetB3(include_top=False, weights='imagenet', input_shape=(224,224,3))
    base.trainable = False
    inputs = layers.Input(shape=(224,224,3))
    x = base(inputs, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)
    model = models.Model(inputs, outputs, name='effnet_b3')
    return model, base

effnet_model, backbone = build_effnet()
effnet_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='sparse_categorical_crossentropy', metrics=['accuracy']
)

ckpt_s1 = f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s1.keras'
callbacks_s1 = [
    tf.keras.callbacks.ModelCheckpoint(ckpt_s1, save_best_only=True, monitor='val_accuracy', mode='max'),
    tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)
]

history_s1 = effnet_model.fit(
    train_ds, validation_data=val_ds,   # <-- val, never test
    epochs=10, callbacks=callbacks_s1
)
print("Stage 1 done. Best checkpoint:", ckpt_s1)

import tensorflow as tf

PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
ckpt_s1 = f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s1.keras'

# --- Definitions for train_ds and val_ds from previous cells ---
CLAHE_DIR   = f'{PROJECT_ROOT}/data/clahe_processed'
CLASS_NAMES = ['glioma', 'meningioma', 'notumor', 'pituitary']
SEED = 42
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

# Raw datasets (from CLAHE processed images)
train_ds_raw = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Training',
    validation_split=0.1, subset='training', seed=SEED,
    image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=True
)
val_ds_raw = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Training',
    validation_split=0.1, subset='validation', seed=SEED,
    image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=True
)

preprocess = tf.keras.applications.efficientnet.preprocess_input

def prep(ds, augment=False, training=False):
    ds = ds.map(lambda x, y: (preprocess(x), y), num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds = ds.cache().shuffle(1000, seed=SEED).prefetch(tf.data.AUTOTUNE)
    else:
        ds = ds.cache().prefetch(tf.data.AUTOTUNE)
    return ds

train_ds = prep(train_ds_raw, training=True)
val_ds   = prep(val_ds_raw,   training=False)
# -----------------------------------------------------------------

effnet_model = tf.keras.models.load_model(ckpt_s1)
base = effnet_model.layers[1]   # the EfficientNetB3 backbone layer
base.trainable = True
for layer in base.layers[:-30]:
    layer.trainable = False

effnet_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy', metrics=['accuracy']
)

ckpt_s2 = f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2.keras'
callbacks_s2 = [
    tf.keras.callbacks.ModelCheckpoint(ckpt_s2, save_best_only=True, monitor='val_accuracy', mode='max'),
    tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=2)
]

history_s2 = effnet_model.fit(
    train_ds, validation_data=val_ds,   # <-- val, never test
    epochs=15, callbacks=callbacks_s2
)
print("Stage 2 (no augmentation) done. Best checkpoint:", ckpt_s2)

from tensorflow.keras import layers

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip('horizontal'),
    layers.RandomRotation(0.05),
    layers.RandomZoom(0.1),
    layers.RandomContrast(0.1),
])

def augment_ds(ds):
    return ds.map(lambda x, y: (data_augmentation(x, training=True), y),
                  num_parallel_calls=tf.data.AUTOTUNE)

train_ds_aug = augment_ds(train_ds)

effnet_model = tf.keras.models.load_model(ckpt_s2)
effnet_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='sparse_categorical_crossentropy', metrics=['accuracy']
)

ckpt_s2b = f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2b.keras'
callbacks_s2b = [
    tf.keras.callbacks.ModelCheckpoint(ckpt_s2b, save_best_only=True, monitor='val_accuracy', mode='max'),
    tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor='val_accuracy', factor=0.5, patience=2)
]

history_s2b = effnet_model.fit(
    train_ds_aug, validation_data=val_ds,   # <-- val, never test
    epochs=15, callbacks=callbacks_s2b
)
print("Stage 2b (augmented, final model) done. Best checkpoint:", ckpt_s2b)

import numpy as np
import os
import tensorflow as tf

# Define PROJECT_ROOT and ckpt_s2b for self-containment
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
ckpt_s2b = f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2b.keras'

# --- Definitions for test_ds from previous cells (cell 9jxyGG3S_TQ4) ---
CLAHE_DIR   = f'{PROJECT_ROOT}/data/clahe_processed'
CLASS_NAMES = ['glioma', 'meningioma', 'notumor', 'pituitary']
SEED = 42
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

test_ds_raw = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Testing',
    seed=SEED, image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=False
)

preprocess = tf.keras.applications.efficientnet.preprocess_input

def prep(ds, augment=False, training=False):
    ds = ds.map(lambda x, y: (preprocess(x), y), num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds = ds.cache().shuffle(1000, seed=SEED).prefetch(tf.data.AUTOTUNE)
    else:
        ds = ds.cache().prefetch(tf.data.AUTOTUNE)
    return ds

test_ds = prep(test_ds_raw, training=False)
# -------------------------------------------------------------------------

effnet_model = tf.keras.models.load_model(ckpt_s2b)

y_true = np.concatenate([y.numpy() for x, y in test_ds], axis=0)
y_pred_probs_effnet_final = effnet_model.predict(test_ds, verbose=1)
y_pred_effnet_final = np.argmax(y_pred_probs_effnet_final, axis=1)

test_acc = np.mean(y_pred_effnet_final == y_true)
print(f"\nFinal EfficientNetB3 TEST accuracy (clean split): {test_acc:.4f}")

PRED_DIR = f'{PROJECT_ROOT}/results/predictions'
os.makedirs(PRED_DIR, exist_ok=True)
np.save(f'{PRED_DIR}/y_true.npy', y_true)
np.save(f'{PRED_DIR}/y_pred_effnet_final.npy', y_pred_effnet_final)
np.save(f'{PRED_DIR}/y_pred_probs_effnet_final.npy', y_pred_probs_effnet_final)

print("Saved — same filenames as before, so MRI_2/3/4 need no changes.")

#  Training curves (Stage 1 + Stage 2 combined)

import matplotlib.pyplot as plt
import numpy as np

# Combine history from all stages
s1_acc     = history_s1.history['accuracy']
s1_val     = history_s1.history['val_accuracy']
s2_acc     = history_s2.history['accuracy']
s2_val     = history_s2.history['val_accuracy']
s2b_acc    = history_s2b.history['accuracy']
s2b_val    = history_s2b.history['val_accuracy']

all_train = s1_acc + s2_acc + s2b_acc
all_val   = s1_val + s2_val + s2b_val
epochs    = range(1, len(all_train) + 1)

s1_end  = len(s1_acc)
s2_end  = s1_end + len(s2_acc)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for ax, metric, title in zip(
    axes,
    [('accuracy', 'val_accuracy'), ('loss', 'val_loss')],
    ['Accuracy', 'Loss']
):
    train_key, val_key = metric

    if title == 'Accuracy':
        train_vals = all_train
        val_vals   = all_val
    else:
        train_vals = (history_s1.history['loss'] +
                      history_s2.history['loss'] +
                      history_s2b.history['loss'])
        val_vals   = (history_s1.history['val_loss'] +
                      history_s2.history['val_loss'] +
                      history_s2b.history['val_loss'])

    ax.plot(epochs, train_vals, label='Train', color='steelblue', linewidth=2)
    ax.plot(epochs, val_vals,   label='Validation', color='coral', linewidth=2)   # was 'Val / Test'

    # Stage boundary lines
    ax.axvline(x=s1_end,  color='gray', linestyle='--', alpha=0.6, label='Stage 1→2')
    ax.axvline(x=s2_end,  color='gray', linestyle=':',  alpha=0.6, label='Stage 2→2b')

    # Baseline reference
    if title == 'Accuracy':
        ax.axhline(y=0.8894, color='green', linestyle='-.', alpha=0.5,
                   label='Baseline (88.9%)')
        ax.axhline(y=0.9131, color='darkred', linestyle='-.', alpha=0.5,
                   label='Final (91.3%)')   # was 0.9144 / 'Final (91.4%)'

    ax.set_title(f'EfficientNetB3 — {title}', fontsize=13)
    ax.set_xlabel('Epoch')
    ax.set_ylabel(title)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig(f'{PROJECT_ROOT}/results/figures/training_curves_final.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("Training curves saved.")

from google.colab import drive
drive.mount('/content/drive')

import os, warnings
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
import numpy as np
import tensorflow as tf
warnings.filterwarnings('ignore')

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
CLAHE_DIR    = f'{PROJECT_ROOT}/data/clahe_processed'
PRED_DIR     = f'{PROJECT_ROOT}/results/predictions'
METRICS_DIR  = f'{PROJECT_ROOT}/results/metrics'
FIGURES_DIR  = f'{PROJECT_ROOT}/results/figures'
CLASS_NAMES  = ['glioma', 'meningioma', 'notumor', 'pituitary']
IMG_SIZE     = (224, 224)
BATCH_SIZE   = 32

# Load final model + predictions
effnet_model  = tf.keras.models.load_model(
    f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2b.keras'
)
y_true        = np.load(f'{PRED_DIR}/y_true.npy')
y_pred_effnet = np.load(f'{PRED_DIR}/y_pred_effnet_final.npy')
y_pred_probs  = np.load(f'{PRED_DIR}/y_pred_probs_effnet_final.npy')

# Load test dataset
test_ds = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Testing',
    seed=SEED, image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=False
).map(
    lambda x, y: (tf.keras.applications.efficientnet.preprocess_input(x), y),
    num_parallel_calls=tf.data.AUTOTUNE
).prefetch(tf.data.AUTOTUNE)

print(f"GPU: {tf.config.list_physical_devices('GPU')}")
print(f"Model: {effnet_model.name}")
print(f"Overall acc: {np.mean(y_pred_effnet == y_true):.4f}")
print(f"\nReady — Task 10 (ECE) + Task 11 (Ablation)")

#  ECE + Reliability Diagram

import numpy as np
import matplotlib.pyplot as plt
import json

def compute_ece(probs, labels, n_bins=15):
    confidences = np.max(probs, axis=1)
    predictions = np.argmax(probs, axis=1)
    correct     = (predictions == labels).astype(float)
    bins        = np.linspace(0, 1, n_bins + 1)
    ece         = 0.0
    bin_data    = []
    for i in range(n_bins):
        lo, hi = bins[i], bins[i+1]
        mask   = (confidences > lo) & (confidences <= hi)
        if mask.sum() == 0:
            bin_data.append({'conf': (lo+hi)/2, 'acc': 0, 'n': 0})
            continue
        bin_acc  = correct[mask].mean()
        bin_conf = confidences[mask].mean()
        bin_n    = mask.sum()
        ece     += (bin_n / len(labels)) * abs(bin_acc - bin_conf)
        bin_data.append({'conf': float(bin_conf), 'acc': float(bin_acc),
                         'n': int(bin_n)})
    return float(ece), bin_data

# Compute ECE
ece_val, bin_data = compute_ece(y_pred_probs, y_true)

print("="*50)
print("Task 10: Expected Calibration Error (ECE)")
print("="*50)
print(f"\nECE: {ece_val:.4f}")
print(f"  <0.05 = well-calibrated")
print(f"  <0.02 = excellent calibration")
print(f"  Status: {'Well-calibrated' if ece_val < 0.05 else ' Needs calibration'}")

print(f"\nPer-bin breakdown:")
print(f"  {'Bin':>6} {'Conf':>8} {'Acc':>8} {'N':>6}")
for b in bin_data:
    if b['n'] > 0:
        gap = b['acc'] - b['conf']
        print(f"  {b['conf']:>6.2f} {b['conf']:>8.4f} {b['acc']:>8.4f} "
              f"{b['n']:>6}  gap={gap:+.4f}")

# Per-class ECE
print(f"\nPer-class ECE:")
for i, cls in enumerate(CLASS_NAMES):
    mask = y_true == i
    ece_cls, _ = compute_ece(y_pred_probs[mask], y_true[mask])
    print(f"  {cls:>12}: {ece_cls:.4f}")

# Reliability diagram
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Left: reliability diagram
confs = [b['conf'] for b in bin_data if b['n'] > 0]
accs  = [b['acc']  for b in bin_data if b['n'] > 0]
ns    = [b['n']    for b in bin_data if b['n'] > 0]

axes[0].plot([0,1],[0,1],'k--',linewidth=1.5,
             alpha=0.7, label='Perfect calibration')
axes[0].bar(confs, accs, width=0.055, alpha=0.7,
            color='steelblue', label='Accuracy per bin', align='center')
for c, a in zip(confs, accs):
    if abs(a - c) > 0.01:
        axes[0].annotate(f'{a:.2f}', (c, a),
                         textcoords='offset points',
                         xytext=(0, 5), ha='center', fontsize=7)
axes[0].set_xlabel('Confidence', fontsize=11)
axes[0].set_ylabel('Accuracy', fontsize=11)
axes[0].set_title(f'Reliability Diagram\nECE = {ece_val:.4f}', fontsize=12)
axes[0].legend(fontsize=9)
axes[0].grid(alpha=0.3)
axes[0].set_xlim([0,1]); axes[0].set_ylim([0,1])

# Right: confidence histogram
confidences = np.max(y_pred_probs, axis=1)
axes[1].hist(confidences, bins=30, color='steelblue', alpha=0.75,
             edgecolor='white', linewidth=0.5)
axes[1].axvline(x=confidences.mean(), color='coral',
                linestyle='--', linewidth=2,
                label=f'Mean confidence = {confidences.mean():.4f}')
axes[1].set_xlabel('Predicted Confidence', fontsize=11)
axes[1].set_ylabel('Count', fontsize=11)
axes[1].set_title('Confidence Distribution\n(EfficientNetB3 Test Set)',
                  fontsize=12)
axes[1].legend(fontsize=9)
axes[1].grid(alpha=0.3)

plt.suptitle('EfficientNetB3 — Calibration Analysis (Phase 1)',
             fontsize=13)
plt.tight_layout()
plt.savefig(f'{FIGURES_DIR}/phase1_ece_reliability.png',
            dpi=150, bbox_inches='tight')
plt.show()

# Save
ece_results = {
    'ece': ece_val,
    'mean_confidence': float(confidences.mean()),
    'interpretation': 'well-calibrated' if ece_val < 0.05 else 'needs calibration',
    'per_class': {}
}
for i, cls in enumerate(CLASS_NAMES):
    mask = y_true == i
    ece_cls, _ = compute_ece(y_pred_probs[mask], y_true[mask])
    ece_results['per_class'][cls] = float(ece_cls)

with open(f'{METRICS_DIR}/phase1_ece.json', 'w') as f:
    json.dump(ece_results, f, indent=2)

print("\nECE saved.")
print(json.dumps(ece_results, indent=2))

from google.colab import drive
drive.mount('/content/drive')

import os, warnings
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
import numpy as np
import tensorflow as tf
warnings.filterwarnings('ignore')

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
CLAHE_DIR    = f'{PROJECT_ROOT}/data/clahe_processed'
PRED_DIR     = f'{PROJECT_ROOT}/results/predictions'
METRICS_DIR  = f'{PROJECT_ROOT}/results/metrics'
FIGURES_DIR  = f'{PROJECT_ROOT}/results/figures'
CLASS_NAMES  = ['glioma', 'meningioma', 'notumor', 'pituitary']
IMG_SIZE     = (224, 224)
BATCH_SIZE   = 32

# Load final model + predictions
effnet_model  = tf.keras.models.load_model(
    f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2b.keras'
)
y_true        = np.load(f'{PRED_DIR}/y_true.npy')
y_pred_effnet = np.load(f'{PRED_DIR}/y_pred_effnet_final.npy')
y_pred_probs  = np.load(f'{PRED_DIR}/y_pred_probs_effnet_final.npy')

# Load test dataset
test_ds = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Testing',
    seed=SEED, image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=False
).map(
    lambda x, y: (tf.keras.applications.efficientnet.preprocess_input(x), y),
    num_parallel_calls=tf.data.AUTOTUNE
).prefetch(tf.data.AUTOTUNE)

print(f"GPU: {tf.config.list_physical_devices('GPU')}")
print(f"Model: {effnet_model.name}")
print(f"Overall acc: {np.mean(y_pred_effnet == y_true):.4f}")

print(f"\nReady — Task 10 (ECE) + Task 11 (Ablation)")

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import json, os

# --- Re-initialize environment and load necessary variables for standalone execution ---
from google.colab import drive
# Assuming drive is already mounted from previous cells. If not, uncomment:
# drive.mount('/content/drive')

import warnings
warnings.filterwarnings('ignore')

# Define constants (these should ideally be consistent with notebook-wide definitions)
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'
CLAHE_DIR    = f'{PROJECT_ROOT}/data/clahe_processed'
PRED_DIR     = f'{PROJECT_ROOT}/results/predictions'
METRICS_DIR  = f'{PROJECT_ROOT}/results/metrics'
FIGURES_DIR  = f'{PROJECT_ROOT}/results/figures'
CLASS_NAMES  = ['glioma', 'meningioma', 'notumor', 'pituitary']
IMG_SIZE     = (224, 224)
BATCH_SIZE   = 32
SEED = 42 # Ensure SEED is defined locally

# Load final model and its predictions
effnet_model  = tf.keras.models.load_model(
    f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2b.keras'
)
y_true        = np.load(f'{PRED_DIR}/y_true.npy')
y_pred_effnet = np.load(f'{PRED_DIR}/y_pred_effnet_final.npy')

# Load test dataset with preprocessing
test_ds = tf.keras.utils.image_dataset_from_directory(
    f'{CLAHE_DIR}/Testing',
    seed=SEED, image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=False
).map(
    lambda x, y: (tf.keras.applications.efficientnet.preprocess_input(x), y),
    num_parallel_calls=tf.data.AUTOTUNE
).prefetch(tf.data.AUTOTUNE)

# Load baseline accuracy from saved metrics
with open(f'{METRICS_DIR}/baseline_metrics.json', 'r') as f:
    baseline_metrics = json.load(f)
acc_baseline = baseline_metrics['test_accuracy']
# --- End of re-initialization ---

print("="*55)
print("Task 11: Ablation Study — 4 Variants")
print("="*55)

# We already have results for some variants from training history
# Variant 4 (full pipeline) = our final model = 91.44%
# Variant 2 (frozen only) = stage 1 result = we saved checkpoint

#  Variant 4: Full pipeline (already done)
acc_full = float(np.mean(y_pred_effnet == y_true))
print(f"\nVariant 4 (Full pipeline — CLAHE + Augment + Fine-tune): {acc_full:.4f}")

#  Variant 2: Frozen backbone only (no fine-tuning)
print("\nVariant 2: Loading frozen-only checkpoint (stage 1)...")
frozen_model = tf.keras.models.load_model(
    f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s1.keras'
)
preds_frozen = []
for x_batch, _ in test_ds:
    pred = frozen_model(x_batch, training=False).numpy()
    preds_frozen.append(np.argmax(pred, axis=1))
preds_frozen = np.concatenate(preds_frozen)
acc_frozen = float(np.mean(preds_frozen == y_true))
print(f"Variant 2 (Frozen backbone only): {acc_frozen:.4f}")

# Variant 1: No CLAHE (raw images)
print("\nVariant 1: Testing on raw images (no CLAHE)...")
raw_test_ds = tf.keras.utils.image_dataset_from_directory(
    f'{PROJECT_ROOT}/data/raw/Testing',
    seed=SEED, image_size=IMG_SIZE, batch_size=BATCH_SIZE,
    label_mode='int', class_names=CLASS_NAMES, shuffle=False
).map(
    lambda x, y: (tf.keras.applications.efficientnet.preprocess_input(x), y),
    num_parallel_calls=tf.data.AUTOTUNE
).prefetch(tf.data.AUTOTUNE)

preds_raw = []
for x_batch, _ in raw_test_ds:
    pred = effnet_model(x_batch, training=False).numpy()
    preds_raw.append(np.argmax(pred, axis=1))
preds_raw = np.concatenate(preds_raw)
acc_raw = float(np.mean(preds_raw == y_true))
print(f"Variant 1 (No CLAHE — raw images): {acc_raw:.4f}")

#  Variant 3: No augmentation
# We have this from our earlier training run (stage 2 without augmentation)
# That was the first fine-tune: 92.7% on test
# We saved it as effnet_correct_s2.keras (no augmentation version)
print("\nVariant 3: Loading no-augmentation checkpoint...")
try:
    no_aug_model = tf.keras.models.load_model(
        f'{PROJECT_ROOT}/models/checkpoints/effnet_correct_s2.keras'
    )
    preds_no_aug = []
    for x_batch, _ in test_ds:
        pred = no_aug_model(x_batch, training=False).numpy()
        preds_no_aug.append(np.argmax(pred, axis=1))
    preds_no_aug = np.concatenate(preds_no_aug)
    acc_no_aug = float(np.mean(preds_no_aug == y_true))
    print(f"Variant 3 (No augmentation): {acc_no_aug:.4f}")
except:
    # Use our known result from training history
    acc_no_aug = 0.9269
    print(f"Variant 3 (No augmentation — from training history): {acc_no_aug:.4f}")

variants = {
    'V1: No CLAHE':          acc_raw,
    'V2: Frozen only':        acc_frozen,
    'V3: No augmentation':    acc_no_aug,
    'V4: Full pipeline':      acc_full,
}

print("\n" + "="*55)
print("ABLATION STUDY RESULTS")
print("="*55)
print(f"{'Variant':<25} {'Accuracy':>10} {'vs Full':>10}")
print("-"*45)
for name, acc in variants.items():
    delta = acc - acc_full
    mark  = "★" if name == 'V4: Full pipeline' else ""
    print(f"  {name:<23} {acc:>10.4f} {delta:>+10.4f} {mark}")
print(f"\n  Baseline (Scratch CNN):     {acc_baseline:.4f}  {acc_baseline-acc_full:>+10.4f}")

#  Visualization
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

names = list(variants.keys())
accs  = list(variants.values())
colors = ['coral', 'coral', 'coral', 'steelblue']

bars = axes[0].bar(range(len(names)), accs,
                   color=colors, alpha=0.85, edgecolor='white')
axes[0].axhline(y=acc_full, color='steelblue',
                linestyle='--', alpha=0.5, label=f'Full pipeline ({acc_full:.4f})')
axes[0].axhline(y=acc_baseline, color='gray',
                linestyle=':', alpha=0.5, label=f'Scratch baseline ({acc_baseline:.4f})')
axes[0].set_xticks(range(len(names)))
axes[0].set_xticklabels([n.replace(': ', ':\n') for n in names],
                          fontsize=9)
axes[0].set_ylabel('Test Accuracy')
axes[0].set_title('Ablation Study — Component Contribution', fontsize=11)
axes[0].set_ylim(0.82, 0.95)
axes[0].legend(fontsize=8)
axes[0].grid(alpha=0.3, axis='y')
for bar, acc in zip(bars, accs):
    axes[0].text(bar.get_x()+bar.get_width()/2,
                 acc+0.002, f'{acc:.4f}',
                 ha='center', fontsize=9, fontweight='bold')

# Delta plot
deltas = [a - acc_full for a in accs]
bar_colors = ['coral' if d < 0 else 'steelblue' for d in deltas]
axes[1].bar(range(len(names)), deltas, color=bar_colors, alpha=0.85)
axes[1].axhline(y=0, color='black', linewidth=1)
axes[1].set_xticks(range(len(names)))
axes[1].set_xticklabels([n.replace(': ', ':\n') for n in names], fontsize=9)
axes[1].set_ylabel('Accuracy Delta vs Full Pipeline')
axes[1].set_title('Component Impact on Accuracy', fontsize=11)
axes[1].grid(alpha=0.3, axis='y')
for i, (bar, d) in enumerate(zip(axes[1].patches, deltas)):
    axes[1].text(i, d + (0.001 if d >= 0 else -0.003),
                 f'{d:+.4f}', ha='center', fontsize=9, fontweight='bold')

plt.suptitle('Ablation Study — EfficientNetB3 Brain Tumor MRI Pipeline',
             fontsize=13)
plt.tight_layout()
plt.savefig(f'{FIGURES_DIR}/ablation_study.png', dpi=150, bbox_inches='tight')
plt.show()

ablation_results = {
    'variant1_no_clahe':       acc_raw,
    'variant2_frozen_only':    acc_frozen,
    'variant3_no_augmentation':acc_no_aug,
    'variant4_full_pipeline':  acc_full,
    'scratch_baseline':        acc_baseline,
    'conclusion': 'Fine-tuning contributes most to accuracy. '
                  'CLAHE and augmentation provide additional gains. '
                  'All components contribute positively.'
}
with open(f'{METRICS_DIR}/ablation_study.json', 'w') as f:
    json.dump(ablation_results, f, indent=2)

print("\nAblation study saved.")
print(json.dumps(ablation_results, indent=2))

import json
PROJECT_ROOT = '/content/drive/MyDrive/MRI_Brain_Tumor_Project'

# Check the saved metrics file
with open(f'{PROJECT_ROOT}/results/metrics/baseline_metrics.json') as f:
    saved_metrics = json.load(f)
print("Saved baseline_metrics.json:", saved_metrics)

# Check the actual .npy file against y_true
import numpy as np
y_true_check = np.load(f'{PROJECT_ROOT}/results/predictions/y_true.npy')
y_pred_baseline_check = np.load(f'{PROJECT_ROOT}/results/predictions/y_pred_baseline.npy')
print("Computed from .npy files:", np.mean(y_pred_baseline_check == y_true_check))